helm-extra-args: --timeout 600s
check-version-increment: false
debug: true
chart-repos:
  - opentelemetry=https://open-telemetry.github.io/opentelemetry-helm-charts
  - prometheus-community=https://prometheus-community.github.io/helm-charts
