---

# The clusters name.
clusterName: ~

# The region the cluster is in.
region: ~

# The environment the cluster is in.
environment: ~

# The service to which a cluster is aligned, i.e infaas, infrastructure
service: ""

# Base URL for the cluster
rootFQDN: ~

ingress:
# Ingress class to use for the cluster
  class: nginx
  privateClass: ~  # internal-nginx
  # Cluster issuer to use for the cluster
  clusterIssuer: letsencrypt-prod

# Prefix for the secret in vault <region/cluster-name>
secretPrefix: ~

# Create a pool called `core` when creating your cluster that is dedicated to core workloads.
# Setting this to true will add topology.unikorn-cloud.org/node-pool=core to the node selector
useCoreNodePool: false

# OpenTelemetry collector endpoint
otlpEndpoint: ~
