name: IAC Scanning

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'CHANGELOG.md'
  pull_request:
    types: [ opened, reopened, synchronize ]
    paths:
      - "charts/**"

jobs:
  scan-k8s-helm:
    name: Scan K8S Code
    runs-on: ubuntu-24.04
    permissions:
      contents: write
      security-events: write
      actions: read
    steps:
      - uses: nscaledev/actions/iac/k8s-helm-manifest-scan@dd2e8c5514b7250ab3fe86cb08fae7ce7366c540
        with:
          harbor-robot-username: ${{ secrets.HARBOR_GHCR_ROBOT_USERNAME }}
          harbor-robot-secret: ${{ secrets.HARBOR_GHCR_ROBOT_SECRET }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          trivyignore-from-s3: true
          trivyignore-file: .trivyignore
          s3-endpoint: ${{ secrets.S3_ENDPOINT }}
          s3-access-key: ${{ secrets.S3_ACCESS_KEY }}
          s3-secret-key: ${{ secrets.S3_SECRET_KEY }}
          s3-region: glo1
          s3-bucket: trivyignores
          s3-path: argocd-apps-k8s
          scan-fail-on-detection: 0
