name: IAC Scanning

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'CHANGELOG.md'
  pull_request:
    types: [ opened, reopened, synchronize ]
    paths:
      - "charts/**"
  workflow_dispatch:

jobs:
  scan-k8s-helm:
    name: Scan K8S Code
    runs-on: ubuntu-24.04
    permissions:
      contents: write
      security-events: write
      actions: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate Trivy Config file
        shell: bash
        run: |
          cat <<EOF > trivy.yaml
          misconfiguration:
            scanners:
              - kubernetes
              - helm
          EOF

      - name: Run Trivy in GitHub SBOM mode and submit results to Dependency Graph
        uses: aquasecurity/trivy-action@dc5a429b52fcf669ce959baa2c2dd26090d2a6c4
        with:
          scan-type: 'fs'
          format: 'github'
          output: 'dependency-results.sbom.json'
          image-ref: '.'
          github-pat: ${{ secrets.GITHUB_TOKEN }}
        env:
          TRIVY_SKIP_JAVA_DB_UPDATE: true

      - name: Run Trivy vulnerability scanner in IaC mode
        uses: aquasecurity/trivy-action@dc5a429b52fcf669ce959baa2c2dd26090d2a6c4
        id: scan
        with:
          scan-type: 'config'
          hide-progress: true
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'HIGH,CRITICAL'
          trivy-config: 'trivy.yaml'
          exit-code: 1
        env:
          TRIVY_SKIP_DB_UPDATE: true
          TRIVY_SKIP_JAVA_DB_UPDATE: true

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@b6a472f63d85b9c78a3ac5e89422239fc15e9b3c
        if: (success() || failure()) && (steps.scan.conclusion == 'success' || steps.scan.outcome == 'failure')
        with:
          sarif_file: 'trivy-results.sarif'
          token: ${{ secrets.GITHUB_TOKEN }}
